target 'lulu_money_ios' do
    use_frameworks!
    flutter_application_path = '../optimus'
    load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
    install_all_flutter_pods(flutter_application_path)

    pod 'lottie-ios', '2.5.2'
end